"""Export an html-presentation-skill deck to PowerPoint (.pptx) with speaker notes.

Usage:
    python export_to_pptx.py <presentation.html> [-o output.pptx]

The script:
  1. Spins up a local HTTP server so external fonts (e.g. Google Fonts) load correctly.
  2. Uses a headless Chromium browser to screenshot each slide at 2x device pixel
     ratio (3840x2160) for sharp output.
  3. Parses speaker notes from the HTML and embeds them in the PowerPoint notes pane.

Compatibility:
    Designed for presentations generated by the html-presentation-skill, which uses
    <div id="sN" class="slide"> containers and <div class="speaker-notes"> elements.
"""

import argparse
import asyncio
import re
import threading
import http.server
import socketserver
import os
import sys
from pathlib import Path
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeoutError
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import io
from PIL import Image

SLIDE_W: float = 13.33
SLIDE_H: float = 7.5
VIEWPORT_W: int = 1920
VIEWPORT_H: int = 1080
DEVICE_SCALE: int = 2
PORT: int = 8765
_PNG_DPI: int = round(VIEWPORT_W * DEVICE_SCALE / SLIDE_W)


def _stamp_dpi(img_bytes: bytes, dpi: int) -> bytes:
    """Re-encode a PNG with explicit DPI metadata.

    Playwright screenshots contain no DPI chunk, which causes PowerPoint to
    treat images as 72 DPI and auto-compress them on save.  Stamping the
    correct DPI (pixels-per-inch at the intended display size) prevents that
    compression and ensures sharp rendering.

    Args:
        img_bytes: Raw PNG bytes from Playwright's screenshot call.
        dpi: Intended display density in pixels per inch, e.g.
             round(VIEWPORT_W * DEVICE_SCALE / SLIDE_W) = 288 for a
             3840 px image placed at 13.33 inches.

    Returns:
        PNG bytes with a pHYs DPI chunk set to (dpi, dpi).

    Raises:
        ValueError: If img_bytes is empty or not a valid PNG.
        RuntimeError: If Pillow cannot re-encode the image.
    """
    if not img_bytes:
        raise ValueError("img_bytes is empty; screenshot may have failed.")
    try:
        buf = io.BytesIO(img_bytes)
        img = Image.open(buf)
        img.verify()
    except Exception as e:
        raise ValueError(f"img_bytes is not a valid PNG: {e}") from e
    try:
        buf = io.BytesIO(img_bytes)
        img = Image.open(buf)
        out = io.BytesIO()
        img.save(out, format="PNG", dpi=(dpi, dpi))
        return out.getvalue()
    except Exception as e:
        raise RuntimeError(f"Failed to re-encode PNG with DPI={dpi}: {e}") from e


def start_server(directory: Path) -> socketserver.TCPServer:
    """Start a local HTTP server serving files from the given directory.

    Args:
        directory: The directory to serve files from.

    Returns:
        The running TCPServer instance.

    Raises:
        OSError: If the port is already in use.
    """
    os.chdir(directory)
    handler = http.server.SimpleHTTPRequestHandler
    handler.log_message = lambda *a: None
    try:
        httpd = socketserver.TCPServer(("", PORT), handler)
    except OSError as e:
        raise OSError(
            f"Could not start HTTP server on port {PORT}: {e}. "
            f"Another process may be using that port. "
            f"Find and kill it with: lsof -ti :{PORT} | xargs kill -9"
        ) from e
    t = threading.Thread(target=httpd.serve_forever, daemon=True)
    t.start()
    return httpd


def extract_slide_data(html_path: Path) -> list[dict]:
    """Parse slide IDs and speaker notes from an html-presentation-skill HTML file.

    Slides are identified by <div id="sN"> elements. Speaker notes are extracted
    from nested <div class="speaker-notes"> elements.

    Args:
        html_path: Path to the HTML presentation file.

    Returns:
        List of dicts with keys 'id' (str) and 'notes' (str).

    Raises:
        ValueError: If no slides are found in the HTML file.
    """
    try:
        soup = BeautifulSoup(html_path.read_text(encoding="utf-8"), "html.parser")
    except UnicodeDecodeError as e:
        raise OSError(
            f"Could not decode '{html_path.name}' as UTF-8: {e}. "
            "Ensure the file is saved with UTF-8 encoding."
        ) from e
    except OSError as e:
        raise OSError(
            f"Could not read '{html_path.name}': {e}. "
            "Check the file exists and you have read permissions."
        ) from e

    slides = []
    for div in soup.find_all("div", id=re.compile(r"^s\d+$")):
        notes_div = div.find("div", class_="speaker-notes")
        notes = notes_div.get_text(separator=" ", strip=True) if notes_div else ""
        slides.append({"id": div["id"], "notes": notes})

    if not slides:
        raise ValueError(
            f"No slides found in {html_path.name}. "
            "Expected <div id='sN'> elements (s1, s2, ...). "
            "Is this a valid html-presentation-skill file?"
        )
    return slides


async def screenshot_slides(html_filename: str, slide_ids: list[str]) -> list[bytes]:
    """Screenshot each slide using a headless Chromium browser.

    Hides navigation UI and forces all animation classes to their final visible
    state so slides render fully without waiting for JS-driven transitions.

    Args:
        html_filename: Filename (not path) of the HTML file, served via localhost.
        slide_ids: Ordered list of slide element IDs to capture.

    Returns:
        List of PNG image bytes, one per slide, in the same order as slide_ids.

    Raises:
        RuntimeError: If the page fails to load or a slide cannot be captured.
    """
    screenshots = []
    try:
        async with async_playwright() as p:
            try:
                browser = await p.chromium.launch()
            except Exception as e:
                raise RuntimeError(
                    f"Failed to launch Chromium: {e}. "
                    "Try running: python -m playwright install chromium"
                ) from e

            page = await browser.new_page(
                viewport={"width": VIEWPORT_W, "height": VIEWPORT_H},
                device_scale_factor=DEVICE_SCALE,
            )

            try:
                await page.goto(
                    f"http://localhost:{PORT}/{html_filename}",
                    timeout=15000,
                )
                await page.wait_for_load_state("networkidle", timeout=15000)
            except PlaywrightTimeoutError as e:
                raise RuntimeError(
                    f"Page failed to load within 15s: {e}. "
                    f"Verify the file is being served at http://localhost:{PORT}/{html_filename} "
                    f"and that no firewall or proxy is blocking localhost connections."
                ) from e

            try:
                await page.evaluate("document.fonts.ready")
            except Exception as e:
                print(f"  Warning: font readiness check failed ({e}), continuing anyway.")

            await page.wait_for_timeout(500)

            await page.add_style_tag(content="""
                #nav { display: none !important; }
                .speaker-notes { display: none !important; }
                #notes-panel { display: none !important; }
                *, *::before, *::after {
                    transition: none !important;
                    animation: none !important;
                    animation-duration: 0s !important;
                    transition-duration: 0s !important;
                }
                .anim, .anim-left, .anim-right, .stagger, .scale-pop {
                    opacity: 1 !important;
                    transform: none !important;
                }
            """)

            for slide_id in slide_ids:
                try:
                    await page.evaluate(f"""
                        document.querySelectorAll('.slide').forEach(s => s.classList.remove('active'));
                        const el = document.getElementById('{slide_id}');
                        if (!el) throw new Error('Slide element not found: {slide_id}');
                        el.classList.add('active');
                    """)
                except Exception as e:
                    raise RuntimeError(
                        f"Could not activate slide '{slide_id}': {e}. "
                        f"The element <div id='{slide_id}'> may be missing from the HTML. "
                        "Verify the slide ID exists by searching the HTML file."
                    ) from e

                await page.wait_for_timeout(200)

                try:
                    data = await page.screenshot(
                        type="png",
                        clip={"x": 0, "y": 0, "width": VIEWPORT_W, "height": VIEWPORT_H},
                        scale="device",
                    )
                except Exception as e:
                    raise RuntimeError(
                        f"Screenshot failed for slide '{slide_id}': {e}. "
                        "The browser may have crashed. Try re-running the script; "
                        "if the error persists run: python -m playwright install chromium"
                    ) from e

                screenshots.append(data)
                print(f"  Captured {slide_id}")

            await browser.close()

    except RuntimeError:
        raise
    except Exception as e:
        raise RuntimeError(
            f"Unexpected error during screenshotting: {type(e).__name__}: {e}. "
            "Check that playwright and chromium are installed: "
            "pip install playwright && python -m playwright install chromium"
        ) from e

    return screenshots


def build_pptx(slides: list[dict], screenshots: list[bytes], output: Path) -> None:
    """Assemble a PowerPoint file from slide screenshots and speaker notes.

    Each slide is added as a full-bleed image on a blank layout. Speaker notes
    are written to the PowerPoint notes pane in 11pt dark gray text.

    Args:
        slides: Slide metadata list from extract_slide_data().
        screenshots: PNG bytes list from screenshot_slides(), same order as slides.
        output: Destination path for the .pptx file.

    Raises:
        OSError: If the output file cannot be written.
    """
    prs = Presentation()
    prs.slide_width = Inches(SLIDE_W)
    prs.slide_height = Inches(SLIDE_H)
    blank_layout = prs.slide_layouts[6]

    for i, (slide_data, img_bytes) in enumerate(zip(slides, screenshots)):
        slide = prs.slides.add_slide(blank_layout)
        try:
            slide.shapes.add_picture(
                io.BytesIO(_stamp_dpi(img_bytes, _PNG_DPI)),
                Inches(0), Inches(0),
                Inches(SLIDE_W), Inches(SLIDE_H),
            )
        except Exception as e:
            raise RuntimeError(
                f"Failed to add image for slide {i+1} ({slide_data['id']}): {e}. "
                "The screenshot bytes may be corrupt or empty. "
                "Re-run the script; if the error persists increase wait_for_timeout."
            ) from e

        if slide_data["notes"]:
            notes_slide = slide.notes_slide
            tf = notes_slide.notes_text_frame
            tf.text = slide_data["notes"]
            for para in tf.paragraphs:
                for run in para.runs:
                    run.font.size = Pt(11)
                    run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

        print(f"  Built slide {i+1}/{len(slides)} ({slide_data['id']})")

    try:
        prs.save(output)
    except OSError as e:
        raise OSError(
            f"Could not write output file '{output}': {e}. "
            "Possible causes: the file is open in PowerPoint, the output directory "
            "does not exist, or you do not have write permissions to that path."
        ) from e

    print(f"\nSUCCESS: Exported {len(slides)} slides to {output}")
    print(f"NEXT: Open '{output}' in PowerPoint or Google Slides to review and share.")


async def main(html_file: Path, output_file: Path) -> None:
    """Orchestrate the full export pipeline.

    Args:
        html_file: Absolute path to the HTML presentation file.
        output_file: Destination path for the exported .pptx file.
    """
    print("Starting local HTTP server...")
    httpd = start_server(html_file.parent)
    try:
        print("Parsing HTML...")
        slides = extract_slide_data(html_file)
        print(f"Found {len(slides)} slides")

        print("\nScreenshotting slides...")
        screenshots = await screenshot_slides(html_file.name, [s["id"] for s in slides])

        print("\nBuilding PPTX...")
        build_pptx(slides, screenshots, output_file)
    finally:
        httpd.shutdown()
        print("HTTP server stopped.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export an html-presentation-skill deck to PowerPoint with speaker notes."
    )
    parser.add_argument("html", help="Path to the HTML presentation file.")
    parser.add_argument(
        "-o", "--output",
        help="Output .pptx path (default: same name as HTML file with .pptx extension).",
        default=None,
    )
    args = parser.parse_args()

    html_path = Path(args.html).resolve()
    if not html_path.exists():
        print(f"ERROR: file not found: {html_path}", file=sys.stderr)
        print(f"HINT:  Check the path and ensure the deck file exists.", file=sys.stderr)
        sys.exit(1)

    output_path = Path(args.output).resolve() if args.output else html_path.with_suffix(".pptx")

    try:
        asyncio.run(main(html_path, output_path))
    except (OSError, ValueError, RuntimeError) as e:
        print(f"\nERROR: {e}", file=sys.stderr)
        sys.exit(1)
    except KeyboardInterrupt:
        print("\nCancelled.", file=sys.stderr)
        sys.exit(1)
